# Generated by Django 4.2.16 on 2025-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0002_alter_room_room_size_alter_room_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(max_length=25),
        ),
    ]
