# Generated by Django 4.2.16 on 2025-01-24 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0003_alter_room_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapi.booking'),
        ),
    ]
