# Generated by Django 4.2.8 on 2025-01-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0006_alter_event_description_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapi.event'),
        ),
    ]
